In [2]:
import numpy;
print (numpy.version.version) #numpy version
import pandas as pd;
print (pd.__version__) #numpy version

1.23.5
1.5.3


In [3]:
print ("Hello HCIA PDTP-Huawei Team")

Hello HCIA PDTP-Huawei Team


In [5]:
a = 5
b = 10
sum = a + b
print(sum)

15


In [6]:
t = (1,)
print(t)

(1,)


In [9]:
t = (1, 2, 3)
for i in t:
   print(i)

1
2
3


In [10]:
d = {'name':'Reagan', 'phone':'+254 722 222333'}
print(d)

{'name': 'Reagan', 'phone': '+254 722 222333'}


In [15]:
def Mul(a, b):
    return a * b

print(Mul(8, 6))

48


In [17]:
def sqrProd(x, y):
    return (x * y) ** 2

print(sqrProd(2, 5))

100


In [18]:
import numpy as np
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
import numpy as np
values = np.arange(9)
matrix = values.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


In [21]:
import numpy as np

arr = np.random.randn(10, 10)

min_val = arr.min()
max_val = arr.max()

print(min_val)
print(max_val)

-2.239807228439555
2.7847237809348226


In [22]:
import numpy as np

vec = np.random.randn(30)
mean = np.mean(vec)

print(mean)

0.31714270443579634


In [23]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

product = num1 * num2

print("The product of", num1, "and", num2, "is", product)

Enter the first number: 5
Enter the second number: 12
The product of 5.0 and 12.0 is 60.0


Complete the code for the following function so it matches its documentation:
def doubleList(numberList):
For each of the numbers in the list numberList, print a line containing twice the original


In [36]:
def doubleList(numberList):
  """For each of the numbers in the list numberList,
     print a line containing twice the original number."""

  for number in numberList:
    print(2 * number)

# Example usage
myList = [3, 1, 5]
doubleList(myList)

6
2
10
